### ISSUE TITLE
[Bug] ISSUE_TITLE

### ISSUE THREAD

**Issue by Ryuko-Ryukai** [trickerer01/Ruxx#13]
### DO NOT REMOVE OR SKIP THE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Provide a well enough worded description

Date bug: I search a tag named 'prolapse' , for example, with the date min default it results 3182 files but when I change the date min to 24-02-2024 , it results the same as default. It should be less than 3182 files (maybe 20 or less)

### Provide verbose output that demonstrates the problem (use -verbose | Edit -> Verbose log)

```shell
Cmd: prolapse -module rx -path 'C:/Users/Acer/Dropbox/PC/Downloads/' -threads 8 -mindate 24-02-2024 -timeout 10 -retries 10 -prefix -dump_tags -dump_sources -dump_comments -append_info -warn_nonempty
```

**Comment by trickerer** [comment]
When you click `check` button date filter isn't checked because you cannot filter by date using website API. If you try to download everything works.

<details><summary>Log</summary>
<p>
Python 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)]<br>
Base args: P:/!Ruxx.exe<br>
My args: Cmd: prolapse -module rx -path './!!dwn/t1/' -threads 8 -mindate 24-02-2024 -timeout 15 -retries 20 -prefix -dmode 1 -append_info -verbose
===================================================================================================

(Emulation Mode)

===================================================================================================
Ruxx core ver 1.3 r537
[21:26:32] Starting rx_manual

0 'excluded tags combination' custom filter(s) parsed
1 task(s) scheduled:
prolapse

===================================================================================================

task 1 in progress...
prolapse

Total 3817 item(s) found across 4 page(s)
Looking for min page by date...
Min page: max date irrelevant! Skipping
Looking for max page by date...
step 1
page 3 (div 2, step 1)
Info: TagProc: < mindate at 4138295 - stepping backwards...
step 2
page 2 (div 4, step -1)
Info: TagProc: < mindate at 4138402 - stepping backwards...
step 3
page 1 (div 4, step -1)
Info: TagProc: < mindate at 6984585 - stepping backwards...
step 4
page 0 (div 4, step -1)
Page < minpage, returning minpage!
new totalcount: 1000
Scanning pages 1 - 1
page: 1 / 1	(1-1000 / 1000)
new totalcount: 1000
Filtering trailing back items...
mindate at 24-02-2024, filtering
step 1
index 500 (div 2, step 1)
Info: TagProc_filter: 8294795 exceeds min date (20-07-2023 < 24-02-2024), shuffling backwards...
step 2
index 250 (div 4, step -1)
Info: TagProc_filter: 9012038 exceeds min date (19-11-2023 < 24-02-2024), shuffling backwards...
step 3
index 125 (div 8, step -1)
Info: TagProc_filter: 9368732 exceeds min date (16-01-2024 < 24-02-2024), shuffling backwards...
step 4
index 63 (div 16, step -1)
Info: TagProc_filter: 9560007 exceeds min date (16-02-2024 < 24-02-2024), shuffling backwards...
step 5
index 32 (div 32, step -1)
Info: TagProc_filter: 9610254 exceeds min date (23-02-2024 < 24-02-2024), shuffling backwards...
step 6
index 17 (div 64, step -1)
Info: TagProc_filter: 9657068 does not exceed min date - stepping forward...
step 7
index 24 (div 128, step 1)
Info: TagProc_filter: 9633380 does not exceed min date - stepping forward...
step 8
index 27 (div 256, step 1)
Info: TagProc_filter: 9617623 does not exceed min date - stepping forward...
step 9
index 28 (div 512, step 1)
Info: TagProc_filter: 9615323 does not exceed min date - stepping forward...
step 10
index 29 (div 1000, step 1)
Info: TagProc_filter: 9614249 does not exceed min date - stepping forward...
step 11
index 30 (div 1000, step 1)
Info: TagProc_filter: 9614247 does not exceed min date - stepping forward...
step 12
index 31 (div 1000, step 1)
Info: TagProc_filter: 9614234 does not exceed min date - stepping forward...
step 13
index 32 (div 1000, step 1)
End: reached forw lim at 32!
Filtered out 968 / 1000 items
new totalcount: 32
Filtering trailing front items...
first items filter is irrelevant! Skipping
new totalcount: 32
Filtering items by type...
Both types are enabled! Skipping
new totalcount: 32
Filtering items by previous tasks...
new totalcount: 32
Filtering out existing items...
new totalcount: 32
Filtering out items using custom filters...
new totalcount: 32

Processing 32 item(s), bound 9614234 to 9710291
32 item(s) scheduled, 8 thread(s) max
Working...
</p>
</details>
